apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hdvi-folder-notifier
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      serviceAccountName: moove-data-pipelines@appspot.gserviceaccount.com
      containers:
      - image: app
        name: app
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GCP_PROJECT
          value: moove-data-pipelines
        - name: BUCKET_NAME
          value: moove-incoming-data-u7x4ty
        - name: MONITORED_PREFIXES
          value: Prebind/,Postbind/,test/
        - name: SLACK_CHANNEL
          value: C0123456789   # your channel ID
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: hdvi-folder-notifier-slack-bot-token
              key: latest
        
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        
        # Health Check Probes
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 3
          initialDelaySeconds: 0
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 0

